"use client";

import Link from "next/link";
import { ArrowUp, ChevronDown, Menu, Search, Sparkles, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

function Mark({ className = "h-6 w-6" }: { className?: string }) { return <svg viewBox="0 0 256 256" className={className} fill="currentColor" aria-hidden="true"><path d="M144 256 27.598 256 144 139.598ZM256 207.5 200 256 200 56 0 56 48 0 256 0ZM0 204.402V112l92.402 92.402Z" /></svg>; }

export function RateThatAiHero() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const router = useRouter();
  const search = () => router.push(query.trim() ? `/database?q=${encodeURIComponent(query.trim())}` : "/database");
  const links = [["Database", "/database"], ["Method", "/methodology"], ["Policy", "/editorial-policy"], ["Nominate a tool", "/submit"]] as const;

  return <section className="landing-page relative flex min-h-[100svh] flex-col overflow-hidden bg-[#e9e7df] bg-cover bg-center text-gray-900" style={{ backgroundImage: "url('/images/rate-that-ai-mountain-hero.png')" }}>
    <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(250,249,245,.76),rgba(255,255,255,.34),rgba(250,249,245,.76))]" aria-hidden="true" />
    <nav className="animate-fade-down relative z-20 flex items-center justify-between px-5 py-4 sm:px-8 sm:py-5 lg:px-10"><Link href="/" className="flex items-center gap-2 text-gray-900"><Mark /><span className="text-sm font-semibold tracking-tight">Rate That AI</span></Link><div className="hidden items-center gap-8 text-[13px] text-gray-700 md:flex"><Link href="/database" className="flex items-center gap-1 hover:text-gray-900">Database <ChevronDown className="h-3.5 w-3.5" /></Link><Link href="/methodology">Method</Link><Link href="/editorial-policy">Policy</Link></div><div className="flex items-center gap-3"><Link href="/submit" className="hidden rounded-full bg-gray-900 px-5 py-2 text-[13px] font-medium text-white hover:bg-gray-800 sm:inline">Nominate a tool</Link><button onClick={() => setOpen(!open)} className="rounded-full p-2 text-gray-900 hover:bg-gray-900/10 md:hidden" aria-label="Toggle navigation">{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open && <div className="animate-fade-up absolute left-4 right-4 top-full z-30 rounded-2xl bg-white/85 px-5 py-3 shadow-xl backdrop-blur-xl ring-1 ring-gray-200 md:hidden">{links.map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)} className="block border-b border-gray-200 py-3 text-[15px] text-gray-700 last:border-0">{label}</Link>)}</div>}</nav>
    <div className="flex-1 min-h-12 shrink-0 sm:min-h-16 lg:min-h-20" />
    <div className="relative z-10 mx-auto flex w-full max-w-5xl flex-col items-center px-5 pb-6 text-center sm:px-8"><p className="animate-fade-up mb-5 rounded-full border border-slate-700/20 bg-white/55 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700 backdrop-blur-sm">Independent AI tool reviews</p><h1 className="text-[46px] font-normal leading-[1.02] tracking-tight text-gray-900 min-[400px]:text-[52px] sm:text-7xl lg:text-8xl xl:text-[88px]"><span className="animate-fade-up block">Find the tools.</span><span className="animate-fade-up block [animation-delay:100ms]">Keep the receipts.</span></h1><form onSubmit={(event) => { event.preventDefault(); search(); }} className="animate-fade-up mt-8 flex w-full max-w-2xl items-center gap-3 rounded-full bg-white/82 py-2 pl-6 pr-2 shadow-xl shadow-slate-800/10 backdrop-blur-md ring-1 ring-slate-500/20 [animation-delay:220ms]"><Search className="h-5 w-5 text-gray-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="flex-1 bg-transparent py-3 text-base text-gray-900 outline-none placeholder:text-gray-500 sm:text-lg" placeholder="Which AI tool are you considering?" /><button className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-gray-900 text-white transition-transform hover:scale-105 active:scale-95 sm:h-12 sm:w-12" aria-label="Search reviews"><ArrowUp className="h-5 w-5" /></button></form><p className="animate-fade-up mt-5 max-w-xl text-base leading-relaxed text-gray-700 [animation-delay:340ms] sm:text-lg">We test AI promises against actual work<br />— then show you the evidence, not the hype. <Sparkles className="inline h-4 w-4 -mt-1" /></p><div className="animate-fade-up mt-6 flex flex-wrap justify-center gap-3 [animation-delay:460ms]"><Link href="/database" className="rounded-full bg-gray-900 px-7 py-3 text-sm font-medium text-white transition-all hover:bg-gray-800 hover:shadow-lg">Explore verdicts</Link><Link href="/methodology" className="rounded-full bg-white/45 px-7 py-3 text-sm font-medium text-gray-800 ring-1 ring-slate-500/30 backdrop-blur-sm transition-colors hover:bg-white/75">How we test</Link></div></div>
    <div className="flex-1 min-h-14 shrink-0 sm:min-h-20 lg:min-h-24" />
  </section>;
}
