"use client";

import { rerateSchema } from "@/lib/validation";
import { FormEvent, useState } from "react";

export function RerateForm() {
  const [company, setCompany] = useState(""); const [email, setEmail] = useState(""); const [toolName, setToolName] = useState(""); const [reviewUrl, setReviewUrl] = useState(""); const [evidence, setEvidence] = useState(""); const [website, setWebsite] = useState(""); const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = rerateSchema.safeParse({ company, email, toolName, reviewUrl, evidence, website }); if (!result.success) { setStatus("error"); setMessage(result.error.issues[0]?.message ?? "Please check your submission."); return; } setStatus("loading"); setMessage(""); try { const response = await fetch("/api/rerate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(result.data) }); const data = await response.json(); if (!response.ok) { setStatus("error"); setMessage(data.error ?? "Unable to submit your request."); return; } setStatus("success"); setMessage("Request received. We’ll review the evidence and decide whether a new test is warranted."); setEvidence(""); } catch { setStatus("error"); setMessage("Network error. Please try again."); } }
  const inputClass = "w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3 text-sm text-white placeholder:text-zinc-500 focus:border-red-500 focus:outline-none focus:ring-1 focus:ring-red-500";
  return <form onSubmit={submit} className="space-y-5"><div className="sr-only" aria-hidden="true"><label htmlFor="rerate-website">Leave this empty</label><input id="rerate-website" tabIndex={-1} autoComplete="off" value={website} onChange={(event) => setWebsite(event.target.value)} /></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-zinc-300">Company<input required value={company} onChange={(event) => setCompany(event.target.value)} className={`mt-2 ${inputClass}`} /></label><label className="text-sm font-medium text-zinc-300">Work email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className={`mt-2 ${inputClass}`} /></label></div><label className="block text-sm font-medium text-zinc-300">Tool name<input required value={toolName} onChange={(event) => setToolName(event.target.value)} className={`mt-2 ${inputClass}`} /></label><label className="block text-sm font-medium text-zinc-300">Link to the review (optional)<input type="url" value={reviewUrl} onChange={(event) => setReviewUrl(event.target.value)} placeholder="https://ratethatai.com/reviews/..." className={`mt-2 ${inputClass}`} /></label><label className="block text-sm font-medium text-zinc-300">What should we re-test, and what verifiable evidence should we consider?<textarea required minLength={50} maxLength={4000} rows={7} value={evidence} onChange={(event) => setEvidence(event.target.value)} placeholder="Describe product updates, the specific claim you dispute, test access, documentation, and reproducible evidence." className={`mt-2 ${inputClass}`} /></label><button disabled={status === "loading"} className="rounded-lg bg-red-600 px-6 py-3 text-sm font-bold text-white transition hover:bg-red-500 disabled:opacity-60">{status === "loading" ? "Submitting…" : "Request a re-rate"}</button>{message && <p className={`text-sm ${status === "success" ? "text-emerald-400" : "text-red-400"}`} role="status">{message}</p>}</form>;
}
